### ISSUE TITLE
Corrections table: <abbr> only required for abbreviations 

### ISSUE THREAD

**Issue by jeremygillies-ea** [EnvironmentAgency/data-returns-frontend#106]
We are currently using the ```<abbr>``` tag on all column titles in the corrections table. 

Only use when the word is abbreviated.

Fix: remove ```<abbr>``` on Parameter, Value, Unit and (Multiple)

![image](https://cloud.githubusercontent.com/assets/11958497/18121489/ae2e191a-6f5c-11e6-9b16-a707235ba1bb.png)

**Comment by graham-willis-druid** [comment]
Moved to Jira
