### ISSUE TITLE
Hide file upload table and continue button until a file is uploaded

### ISSUE THREAD

**Issue by jeremygillies-ea** [EnvironmentAgency/data-returns-frontend#115]
Hide stuff in red until a file is present AND show upload table if all files are removed

![image](https://cloud.githubusercontent.com/assets/11958497/18673274/1c26a496-7f43-11e6-8ecc-c95dd9636d4f.png)

**Comment by graham-willis-druid** [comment]
This is done

**Comment by graham-willis-druid** [comment]
Moved into Jira
