### ISSUE TITLE
Pre-Pen Testing Issues

### ISSUE THREAD

**Issue by EANEIL** [EnvironmentAgency/data-returns-frontend#74]
[ZAP Scanning Report.pdf](https://github.com/EnvironmentAgency/data-returns-frontend/files/248567/ZAP.Scanning.Report.pdf)

Testing with OWASP tools discovered some issues as per the attached report.

@sgardnerdell-ea @kevinjones1 @IamDanB @emily-stone 
There is also a vulnerability in the open file dialogue

 To replicate:
1) Navigate to the "Choose your file" page.
2) Click the "Choose file" button.
3) DO NOT choose a file.
4) Enter some html that runs some scripting (such as <img href=1 onerror=alert('test')> )
5) The alert will be shown, this could be other malicious code, Sam has been able to open an iframe using this vulnerability.

These issues should be fixed.

**Comment by graham-willis-druid** [comment]
Fixed
