### ISSUE TITLE
Email - Message discrepancy W8.1 IE11

### ISSUE THREAD

**Issue by kevinjones1** [EnvironmentAgency/data-returns-frontend#82]
In W8.1 using IE11 the email error message header is displayed with black header (below)
<img width="1063" alt="dr2050 browserstack w8_1 ie11 email" src="https://cloud.githubusercontent.com/assets/13778602/15390539/29355b8c-1db4-11e6-8404-c0afe1128732.png">

In Chrome OSX the header is shown in red (below), also font size appears smaller.
<img width="1076" alt="dr2050 test environment email" src="https://cloud.githubusercontent.com/assets/13778602/15390578/5d1d05a8-1db4-11e6-902c-43a2704da988.png">

**Comment by jeremygillies-ea** [comment]
No longer an issue
