### ISSUE TITLE
PIN - Message discrepancy W8.1 IE11

### ISSUE THREAD

**Issue by kevinjones1** [EnvironmentAgency/data-returns-frontend#83]
In W8 using IE11 the error message displayed when an incorrect PIN is entered is as below.

The content is the same as that in the Content document for DR2225, except for the header font size and colour.

<img width="1072" alt="dr2225 browserstack w8_1 ie11 pin" src="https://cloud.githubusercontent.com/assets/13778602/15390687/07abc22a-1db5-11e6-94de-6f5e2ff14f57.png">

In Chrome Test environment the Content is shown as below, with a dropdown to display additional text.

<img width="1076" alt="dr2225 test environment pin error" src="https://cloud.githubusercontent.com/assets/13778602/15390764/858b3edc-1db5-11e6-8d80-7413a12d1186.png">

**Comment by jeremygillies-ea** [comment]
No longer an issue
