### ISSUE TITLE
Double header on error page when uploading data structure error file

### ISSUE THREAD

**Issue by jeremygillies-ea** [EnvironmentAgency/data-returns-frontend#84]
To replicate on dev, upload a "no-data.csv" or "no-header.csv" file.

![image](https://cloud.githubusercontent.com/assets/11958497/15431631/ae44bfe0-1ea2-11e6-86f9-f53a62c3b3dc.png)

It should just have "You can't send this file" (remove "Choose your file")

**Comment by graham-willis-druid** [comment]
Closing as page redesigned
