### ISSUE TITLE
No data (header only) CSV file is accepted by service

### ISSUE THREAD

**Issue by jeremygillies-ea** [EnvironmentAgency/data-returns-frontend#86]
This file is accepted but the service - surely it should be prevented. Maybe should be picked up as "no permit number"

![image](https://cloud.githubusercontent.com/assets/11958497/17475791/a82a0a66-5d54-11e6-8c6c-3501e65916f2.png)

[header-row-only.csv.zip](https://github.com/EnvironmentAgency/data-returns-frontend/files/406515/header-row-only.csv.zip)

**Comment by graham-willis-druid** [comment]
No long - rejected by mandatory fields message
