### ISSUE TITLE
DR9020 typo

### ISSUE THREAD

**Issue by timstone** [EnvironmentAgency/data-returns-frontend#91]
<img width="1017" alt="screen shot 2016-08-15 at 13 16 03" src="https://cloud.githubusercontent.com/assets/7448162/17664229/8ada4a5c-62ea-11e6-9a11-599d841b287e.png">

Additional 's' in uses - 'but only uses dashes'

You must use dashes or slashes between numbers. Format the date as YYYY-MM-DD but only uses dashes. You can also use DD-MM-YYYY (or DD/MM/YYYY).

**Comment by graham-willis-druid** [comment]
Fixed
