### ISSUE TITLE
Google mail shows purple text for part of email

### ISSUE THREAD

**Issue by timstone** [EnvironmentAgency/data-returns-frontend#95]
<img width="670" alt="screen shot 2016-08-16 at 14 32 09" src="https://cloud.githubusercontent.com/assets/7448162/17700566/4769c372-63be-11e6-8a79-19fd4fd612b8.png">

<img width="218" alt="screen shot 2016-08-16 at 14 33 05" src="https://cloud.githubusercontent.com/assets/7448162/17700591/60978a64-63be-11e6-8460-35622c156363.png">

**Comment by graham-willis-druid** [comment]
Cannot reproduce: 
![screenshot from 2016-09-22 13-36-53](https://cloud.githubusercontent.com/assets/18460056/18748487/5952897e-80ca-11e6-989e-dfbc59c2d8a6.png)
