### ISSUE TITLE
Choose a file button is not highlighted when using key tabs

### ISSUE THREAD

**Issue by timstone** [EnvironmentAgency/data-returns-frontend#96]
<img width="1050" alt="screen shot 2016-08-16 at 14 45 03" src="https://cloud.githubusercontent.com/assets/7448162/17701201/cd9b89ce-63c0-11e6-97d2-b25fcb387ffb.png">

Example above shows the Continue button highlighted, the 'Choose a file' button should have the same hightlighting.

**Comment by graham-willis-druid** [comment]
Moving into Jira. Not super-trivial; we will need to create tabindex dynamically in the file table. The tabindex should only rotate around the 'choose', the 'mode details' and 'remove' links and the continue button, if visible.
